/*
* Generated file
*
* Generated from: yang module name: fabric-mgr-impl yang module local name: fabric-mgr-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Dec 01 14:15:09 EST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.fabric_mgr.impl;
public class FabricMgrModuleFactory extends org.opendaylight.controller.config.yang.config.fabric_mgr.impl.AbstractFabricMgrModuleFactory {

}
