/*
* Generated file
*
* Generated from: yang module name: vxlan-fabric-ovs-adapter-impl yang module local name: vxlan-fabric-ovs-adapter-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Oct 13 15:28:27 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.vxlan_fabric_ovs_adapter.impl;
public class VxlanFabricOVSAdapterModuleFactory extends org.opendaylight.controller.config.yang.config.vxlan_fabric_ovs_adapter.impl.AbstractVxlanFabricOVSAdapterModuleFactory {

}
