/*
* Generated file
*
* Generated from: yang module name: vxlan-fabric-impl yang module local name: predefine-fabric
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Oct 22 09:49:11 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.vxlan_fabric.impl;
public class PredefineFabricModuleFactory extends org.opendaylight.controller.config.yang.config.vxlan_fabric.impl.AbstractPredefineFabricModuleFactory {

}
