//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.24 at 04:48:53 PM EDT 
//


package com.huawei.enterprise.ce.netconf.api.message.getLLDPSysInfo;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="data"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="lldp"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="lldpSys"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="lldpSysInformation"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="chassisIdSubtype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="chassisId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="sysName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="xmlns1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="content-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="format-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="xmlns1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="message-id" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "data"
})
@XmlRootElement(name = "rpc-reply")
public class RpcReply {

    @XmlElement(required = true)
    protected RpcReply.Data data;
    @XmlAttribute(name = "xmlns1")
    protected String xmlns1;
    @XmlAttribute(name = "message-id")
    protected Integer messageId;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link RpcReply.Data }
     *     
     */
    public RpcReply.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpcReply.Data }
     *     
     */
    public void setData(RpcReply.Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the xmlns1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlns1() {
        return xmlns1;
    }

    /**
     * Sets the value of the xmlns1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlns1(String value) {
        this.xmlns1 = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMessageId(Integer value) {
        this.messageId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="lldp"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="lldpSys"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="lldpSysInformation"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="chassisIdSubtype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="chassisId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="sysName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="xmlns1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="content-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="format-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lldp"
    })
    public static class Data {

        @XmlElement(required = true)
        protected RpcReply.Data.Lldp lldp;

        /**
         * Gets the value of the lldp property.
         * 
         * @return
         *     possible object is
         *     {@link RpcReply.Data.Lldp }
         *     
         */
        public RpcReply.Data.Lldp getLldp() {
            return lldp;
        }

        /**
         * Sets the value of the lldp property.
         * 
         * @param value
         *     allowed object is
         *     {@link RpcReply.Data.Lldp }
         *     
         */
        public void setLldp(RpcReply.Data.Lldp value) {
            this.lldp = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="lldpSys"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="lldpSysInformation"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="chassisIdSubtype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="chassisId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="sysName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="xmlns1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="content-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="format-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lldpSys"
        })
        public static class Lldp {

            @XmlElement(required = true)
            protected RpcReply.Data.Lldp.LldpSys lldpSys;
            @XmlAttribute(name = "xmlns1")
            protected String xmlns1;
            @XmlAttribute(name = "content-version")
            protected Integer contentVersion;
            @XmlAttribute(name = "format-version")
            protected Integer formatVersion;

            /**
             * Gets the value of the lldpSys property.
             * 
             * @return
             *     possible object is
             *     {@link RpcReply.Data.Lldp.LldpSys }
             *     
             */
            public RpcReply.Data.Lldp.LldpSys getLldpSys() {
                return lldpSys;
            }

            /**
             * Sets the value of the lldpSys property.
             * 
             * @param value
             *     allowed object is
             *     {@link RpcReply.Data.Lldp.LldpSys }
             *     
             */
            public void setLldpSys(RpcReply.Data.Lldp.LldpSys value) {
                this.lldpSys = value;
            }

            /**
             * Gets the value of the xmlns1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXmlns1() {
                return xmlns1;
            }

            /**
             * Sets the value of the xmlns1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXmlns1(String value) {
                this.xmlns1 = value;
            }

            /**
             * Gets the value of the contentVersion property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getContentVersion() {
                return contentVersion;
            }

            /**
             * Sets the value of the contentVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setContentVersion(Integer value) {
                this.contentVersion = value;
            }

            /**
             * Gets the value of the formatVersion property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getFormatVersion() {
                return formatVersion;
            }

            /**
             * Sets the value of the formatVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setFormatVersion(Integer value) {
                this.formatVersion = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="lldpSysInformation"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="chassisIdSubtype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="chassisId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="sysName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "lldpSysInformation"
            })
            public static class LldpSys {

                @XmlElement(required = true)
                protected RpcReply.Data.Lldp.LldpSys.LldpSysInformation lldpSysInformation;

                /**
                 * Gets the value of the lldpSysInformation property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link RpcReply.Data.Lldp.LldpSys.LldpSysInformation }
                 *     
                 */
                public RpcReply.Data.Lldp.LldpSys.LldpSysInformation getLldpSysInformation() {
                    return lldpSysInformation;
                }

                /**
                 * Sets the value of the lldpSysInformation property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link RpcReply.Data.Lldp.LldpSys.LldpSysInformation }
                 *     
                 */
                public void setLldpSysInformation(RpcReply.Data.Lldp.LldpSys.LldpSysInformation value) {
                    this.lldpSysInformation = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="chassisIdSubtype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="chassisId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="sysName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "chassisIdSubtype",
                    "chassisId",
                    "sysName"
                })
                public static class LldpSysInformation {

                    @XmlElement(required = true)
                    protected String chassisIdSubtype;
                    @XmlElement(required = true)
                    protected String chassisId;
                    @XmlElement(required = true)
                    protected String sysName;

                    /**
                     * Gets the value of the chassisIdSubtype property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getChassisIdSubtype() {
                        return chassisIdSubtype;
                    }

                    /**
                     * Sets the value of the chassisIdSubtype property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setChassisIdSubtype(String value) {
                        this.chassisIdSubtype = value;
                    }

                    /**
                     * Gets the value of the chassisId property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getChassisId() {
                        return chassisId;
                    }

                    /**
                     * Sets the value of the chassisId property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setChassisId(String value) {
                        this.chassisId = value;
                    }

                    /**
                     * Gets the value of the sysName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getSysName() {
                        return sysName;
                    }

                    /**
                     * Sets the value of the sysName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setSysName(String value) {
                        this.sysName = value;
                    }

                }

            }

        }

    }

}
