//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.21 at 12:14:54 PM EDT 
//


package com.huawei.enterprise.ce.netconf.api.message.getLLDPInfo;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="data"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="lldp"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="lldpInterfaces"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="lldpInterface" maxOccurs="unbounded"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="ifName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="lldpIfInformation"&gt;
 *                                                   &lt;complexType&gt;
 *                                                     &lt;complexContent&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                         &lt;sequence&gt;
 *                                                           &lt;element name="portIdSubtype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                           &lt;element name="portId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                           &lt;element name="portDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                         &lt;/sequence&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/complexContent&gt;
 *                                                   &lt;/complexType&gt;
 *                                                 &lt;/element&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="xmlns1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="content-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="format-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="xmlns1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="message-id" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "data"
})
@XmlRootElement(name = "rpc-reply")
public class RpcReply {

    @XmlElement(required = true)
    protected RpcReply.Data data;
    @XmlAttribute(name = "xmlns1")
    protected String xmlns1;
    @XmlAttribute(name = "message-id")
    protected Integer messageId;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link RpcReply.Data }
     *     
     */
    public RpcReply.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpcReply.Data }
     *     
     */
    public void setData(RpcReply.Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the xmlns1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlns1() {
        return xmlns1;
    }

    /**
     * Sets the value of the xmlns1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlns1(String value) {
        this.xmlns1 = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMessageId(Integer value) {
        this.messageId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="lldp"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="lldpInterfaces"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="lldpInterface" maxOccurs="unbounded"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="ifName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="lldpIfInformation"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;complexContent&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                               &lt;sequence&gt;
     *                                                 &lt;element name="portIdSubtype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                 &lt;element name="portId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                 &lt;element name="portDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                               &lt;/sequence&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/complexContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="xmlns1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="content-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="format-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "lldp"
    })
    public static class Data {

        @XmlElement(required = true)
        protected RpcReply.Data.Lldp lldp;

        /**
         * Gets the value of the lldp property.
         * 
         * @return
         *     possible object is
         *     {@link RpcReply.Data.Lldp }
         *     
         */
        public RpcReply.Data.Lldp getLldp() {
            return lldp;
        }

        /**
         * Sets the value of the lldp property.
         * 
         * @param value
         *     allowed object is
         *     {@link RpcReply.Data.Lldp }
         *     
         */
        public void setLldp(RpcReply.Data.Lldp value) {
            this.lldp = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="lldpInterfaces"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="lldpInterface" maxOccurs="unbounded"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="ifName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="lldpIfInformation"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;complexContent&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                     &lt;sequence&gt;
         *                                       &lt;element name="portIdSubtype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                       &lt;element name="portId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                       &lt;element name="portDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                     &lt;/sequence&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/complexContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="xmlns1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="content-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="format-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "lldpInterfaces"
        })
        public static class Lldp {

            @XmlElement(required = true)
            protected RpcReply.Data.Lldp.LldpInterfaces lldpInterfaces;
            @XmlAttribute(name = "xmlns1")
            protected String xmlns1;
            @XmlAttribute(name = "content-version")
            protected Integer contentVersion;
            @XmlAttribute(name = "format-version")
            protected Integer formatVersion;

            /**
             * Gets the value of the lldpInterfaces property.
             * 
             * @return
             *     possible object is
             *     {@link RpcReply.Data.Lldp.LldpInterfaces }
             *     
             */
            public RpcReply.Data.Lldp.LldpInterfaces getLldpInterfaces() {
                return lldpInterfaces;
            }

            /**
             * Sets the value of the lldpInterfaces property.
             * 
             * @param value
             *     allowed object is
             *     {@link RpcReply.Data.Lldp.LldpInterfaces }
             *     
             */
            public void setLldpInterfaces(RpcReply.Data.Lldp.LldpInterfaces value) {
                this.lldpInterfaces = value;
            }

            /**
             * Gets the value of the xmlns1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXmlns1() {
                return xmlns1;
            }

            /**
             * Sets the value of the xmlns1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXmlns1(String value) {
                this.xmlns1 = value;
            }

            /**
             * Gets the value of the contentVersion property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getContentVersion() {
                return contentVersion;
            }

            /**
             * Sets the value of the contentVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setContentVersion(Integer value) {
                this.contentVersion = value;
            }

            /**
             * Gets the value of the formatVersion property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getFormatVersion() {
                return formatVersion;
            }

            /**
             * Sets the value of the formatVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setFormatVersion(Integer value) {
                this.formatVersion = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="lldpInterface" maxOccurs="unbounded"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="ifName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="lldpIfInformation"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;complexContent&gt;
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                           &lt;sequence&gt;
             *                             &lt;element name="portIdSubtype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                             &lt;element name="portId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                             &lt;element name="portDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                           &lt;/sequence&gt;
             *                         &lt;/restriction&gt;
             *                       &lt;/complexContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "lldpInterface"
            })
            public static class LldpInterfaces {

                @XmlElement(required = true)
                protected List<RpcReply.Data.Lldp.LldpInterfaces.LldpInterface> lldpInterface;

                /**
                 * Gets the value of the lldpInterface property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the lldpInterface property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getLldpInterface().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link RpcReply.Data.Lldp.LldpInterfaces.LldpInterface }
                 * 
                 * 
                 */
                public List<RpcReply.Data.Lldp.LldpInterfaces.LldpInterface> getLldpInterface() {
                    if (lldpInterface == null) {
                        lldpInterface = new ArrayList<RpcReply.Data.Lldp.LldpInterfaces.LldpInterface>();
                    }
                    return this.lldpInterface;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="ifName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="lldpIfInformation"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;complexContent&gt;
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                 &lt;sequence&gt;
                 *                   &lt;element name="portIdSubtype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                   &lt;element name="portId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                   &lt;element name="portDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                 &lt;/sequence&gt;
                 *               &lt;/restriction&gt;
                 *             &lt;/complexContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "ifName",
                    "lldpIfInformation"
                })
                public static class LldpInterface {

                    @XmlElement(required = true)
                    protected String ifName;
                    @XmlElement(required = true)
                    protected RpcReply.Data.Lldp.LldpInterfaces.LldpInterface.LldpIfInformation lldpIfInformation;

                    /**
                     * Gets the value of the ifName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIfName() {
                        return ifName;
                    }

                    /**
                     * Sets the value of the ifName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIfName(String value) {
                        this.ifName = value;
                    }

                    /**
                     * Gets the value of the lldpIfInformation property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link RpcReply.Data.Lldp.LldpInterfaces.LldpInterface.LldpIfInformation }
                     *     
                     */
                    public RpcReply.Data.Lldp.LldpInterfaces.LldpInterface.LldpIfInformation getLldpIfInformation() {
                        return lldpIfInformation;
                    }

                    /**
                     * Sets the value of the lldpIfInformation property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link RpcReply.Data.Lldp.LldpInterfaces.LldpInterface.LldpIfInformation }
                     *     
                     */
                    public void setLldpIfInformation(RpcReply.Data.Lldp.LldpInterfaces.LldpInterface.LldpIfInformation value) {
                        this.lldpIfInformation = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;complexContent&gt;
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *       &lt;sequence&gt;
                     *         &lt;element name="portIdSubtype" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *         &lt;element name="portId" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *         &lt;element name="portDescription" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *       &lt;/sequence&gt;
                     *     &lt;/restriction&gt;
                     *   &lt;/complexContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "portIdSubtype",
                        "portId",
                        "portDescription"
                    })
                    public static class LldpIfInformation {

                        @XmlElement(required = true)
                        protected String portIdSubtype;
                        @XmlElement(required = true)
                        protected String portId;
                        @XmlElement(required = true)
                        protected String portDescription;

                        /**
                         * Gets the value of the portIdSubtype property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getPortIdSubtype() {
                            return portIdSubtype;
                        }

                        /**
                         * Sets the value of the portIdSubtype property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setPortIdSubtype(String value) {
                            this.portIdSubtype = value;
                        }

                        /**
                         * Gets the value of the portId property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getPortId() {
                            return portId;
                        }

                        /**
                         * Sets the value of the portId property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setPortId(String value) {
                            this.portId = value;
                        }

                        /**
                         * Gets the value of the portDescription property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link String }
                         *     
                         */
                        public String getPortDescription() {
                            return portDescription;
                        }

                        /**
                         * Sets the value of the portDescription property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link String }
                         *     
                         */
                        public void setPortDescription(String value) {
                            this.portDescription = value;
                        }

                    }

                }

            }

        }

    }

}
