/**
 * Copyright (c) 2015 Huawei Technologies Co. Ltd. and others. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: vxlan-fabric-ovs-adapter-impl yang module local name: vxlan-fabric-ovs-adapter-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Fri Oct 16 10:56:52 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.vxlan_fabric_ce_netconf_adapter.impl;
public class VxlanFabricCENetconfAdapterModuleFactory extends org.opendaylight.controller.config.yang.config.vxlan_fabric_ce_netconf_adapter.impl.AbstractVxlanFabricCENetconfAdapterModuleFactory {

}
