/*
* Generated file
*
* Generated from: yang module name: uln-mapper-impl yang module local name: uln-mapper-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Mon Nov 09 13:42:52 EST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.uln_mapper.impl;
public class UlnMapperModuleFactory extends org.opendaylight.controller.config.yang.config.uln_mapper.impl.AbstractUlnMapperModuleFactory {

}
