/*
* Generated file
*
* Generated from: yang module name: vxlan-fabric-impl yang module local name: vxlan-fabric-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Tue Oct 13 15:31:10 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.vxlan_fabric.impl;
public class VxlanFabricModuleFactory extends org.opendaylight.controller.config.yang.config.vxlan_fabric.impl.AbstractVxlanFabricModuleFactory {

}
