/**
 * Copyright (c) 2015 Huawei Technologies Co. Ltd. and others. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v1.0 which accompanies this distribution,
 * and is available at http://www.eclipse.org/legal/epl-v10.html
 */

/*
* Generated file
*
* Generated from: yang module name: fabric-mgr-impl yang module local name: fabric-mgr-impl
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Thu Nov 12 15:25:03 EST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.fabric_mgr.impl;
public class FabricMgrModuleFactory extends org.opendaylight.controller.config.yang.config.fabric_mgr.impl.AbstractFabricMgrModuleFactory {

}
