//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 10:31:27 AM EDT 
//


package com.huawei.enterprise.ce.netconf.api.message.getIfIPAddress;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.huawei.enterprise.ce.netconf.api.message.getIfIPAddress package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.huawei.enterprise.ce.netconf.api.message.getIfIPAddress
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RpcReply }
     * 
     */
    public RpcReply createRpcReply() {
        return new RpcReply();
    }

    /**
     * Create an instance of {@link RpcReply.Data }
     * 
     */
    public RpcReply.Data createRpcReplyData() {
        return new RpcReply.Data();
    }

    /**
     * Create an instance of {@link RpcReply.Data.Ifm }
     * 
     */
    public RpcReply.Data.Ifm createRpcReplyDataIfm() {
        return new RpcReply.Data.Ifm();
    }

    /**
     * Create an instance of {@link RpcReply.Data.Ifm.Interfaces }
     * 
     */
    public RpcReply.Data.Ifm.Interfaces createRpcReplyDataIfmInterfaces() {
        return new RpcReply.Data.Ifm.Interfaces();
    }

    /**
     * Create an instance of {@link RpcReply.Data.Ifm.Interfaces.Interface }
     * 
     */
    public RpcReply.Data.Ifm.Interfaces.Interface createRpcReplyDataIfmInterfacesInterface() {
        return new RpcReply.Data.Ifm.Interfaces.Interface();
    }

    /**
     * Create an instance of {@link RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 }
     * 
     */
    public RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 createRpcReplyDataIfmInterfacesInterfaceIfmAm4() {
        return new RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4();
    }

    /**
     * Create an instance of {@link RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs }
     * 
     */
    public RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs createRpcReplyDataIfmInterfacesInterfaceIfmAm4Am4CfgAddrs() {
        return new RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs();
    }

    /**
     * Create an instance of {@link RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs.Am4CfgAddr }
     * 
     */
    public RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs.Am4CfgAddr createRpcReplyDataIfmInterfacesInterfaceIfmAm4Am4CfgAddrsAm4CfgAddr() {
        return new RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs.Am4CfgAddr();
    }

}
