//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.30 at 10:31:27 AM EDT 
//


package com.huawei.enterprise.ce.netconf.api.message.getIfIPAddress;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="data"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="ifm"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="interfaces"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="interface"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="ifName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="ifmAm4"&gt;
 *                                                   &lt;complexType&gt;
 *                                                     &lt;complexContent&gt;
 *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                         &lt;sequence&gt;
 *                                                           &lt;element name="am4CfgAddrs"&gt;
 *                                                             &lt;complexType&gt;
 *                                                               &lt;complexContent&gt;
 *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                                   &lt;sequence&gt;
 *                                                                     &lt;element name="am4CfgAddr"&gt;
 *                                                                       &lt;complexType&gt;
 *                                                                         &lt;complexContent&gt;
 *                                                                           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                                                             &lt;sequence&gt;
 *                                                                               &lt;element name="subnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                                               &lt;element name="addrType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                                               &lt;element name="ifIpAddr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                                             &lt;/sequence&gt;
 *                                                                           &lt;/restriction&gt;
 *                                                                         &lt;/complexContent&gt;
 *                                                                       &lt;/complexType&gt;
 *                                                                     &lt;/element&gt;
 *                                                                   &lt;/sequence&gt;
 *                                                                 &lt;/restriction&gt;
 *                                                               &lt;/complexContent&gt;
 *                                                             &lt;/complexType&gt;
 *                                                           &lt;/element&gt;
 *                                                         &lt;/sequence&gt;
 *                                                       &lt;/restriction&gt;
 *                                                     &lt;/complexContent&gt;
 *                                                   &lt;/complexType&gt;
 *                                                 &lt;/element&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                           &lt;/sequence&gt;
 *                           &lt;attribute name="xmlns1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *                           &lt;attribute name="content-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                           &lt;attribute name="format-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="xmlns1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="message-id" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "data"
})
@XmlRootElement(name = "rpc-reply")
public class RpcReply {

    @XmlElement(required = true)
    protected RpcReply.Data data;
    @XmlAttribute(name = "xmlns1")
    protected String xmlns1;
    @XmlAttribute(name = "message-id")
    protected Integer messageId;

    /**
     * Gets the value of the data property.
     * 
     * @return
     *     possible object is
     *     {@link RpcReply.Data }
     *     
     */
    public RpcReply.Data getData() {
        return data;
    }

    /**
     * Sets the value of the data property.
     * 
     * @param value
     *     allowed object is
     *     {@link RpcReply.Data }
     *     
     */
    public void setData(RpcReply.Data value) {
        this.data = value;
    }

    /**
     * Gets the value of the xmlns1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getXmlns1() {
        return xmlns1;
    }

    /**
     * Sets the value of the xmlns1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setXmlns1(String value) {
        this.xmlns1 = value;
    }

    /**
     * Gets the value of the messageId property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMessageId(Integer value) {
        this.messageId = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="ifm"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="interfaces"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="interface"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="ifName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="ifmAm4"&gt;
     *                                         &lt;complexType&gt;
     *                                           &lt;complexContent&gt;
     *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                               &lt;sequence&gt;
     *                                                 &lt;element name="am4CfgAddrs"&gt;
     *                                                   &lt;complexType&gt;
     *                                                     &lt;complexContent&gt;
     *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                                         &lt;sequence&gt;
     *                                                           &lt;element name="am4CfgAddr"&gt;
     *                                                             &lt;complexType&gt;
     *                                                               &lt;complexContent&gt;
     *                                                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                                                   &lt;sequence&gt;
     *                                                                     &lt;element name="subnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                                     &lt;element name="addrType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                                     &lt;element name="ifIpAddr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                                                   &lt;/sequence&gt;
     *                                                                 &lt;/restriction&gt;
     *                                                               &lt;/complexContent&gt;
     *                                                             &lt;/complexType&gt;
     *                                                           &lt;/element&gt;
     *                                                         &lt;/sequence&gt;
     *                                                       &lt;/restriction&gt;
     *                                                     &lt;/complexContent&gt;
     *                                                   &lt;/complexType&gt;
     *                                                 &lt;/element&gt;
     *                                               &lt;/sequence&gt;
     *                                             &lt;/restriction&gt;
     *                                           &lt;/complexContent&gt;
     *                                         &lt;/complexType&gt;
     *                                       &lt;/element&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                 &lt;/sequence&gt;
     *                 &lt;attribute name="xmlns1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
     *                 &lt;attribute name="content-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *                 &lt;attribute name="format-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "ifm"
    })
    public static class Data {

        @XmlElement(required = true)
        protected RpcReply.Data.Ifm ifm;

        /**
         * Gets the value of the ifm property.
         * 
         * @return
         *     possible object is
         *     {@link RpcReply.Data.Ifm }
         *     
         */
        public RpcReply.Data.Ifm getIfm() {
            return ifm;
        }

        /**
         * Sets the value of the ifm property.
         * 
         * @param value
         *     allowed object is
         *     {@link RpcReply.Data.Ifm }
         *     
         */
        public void setIfm(RpcReply.Data.Ifm value) {
            this.ifm = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="interfaces"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="interface"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="ifName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="ifmAm4"&gt;
         *                               &lt;complexType&gt;
         *                                 &lt;complexContent&gt;
         *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                     &lt;sequence&gt;
         *                                       &lt;element name="am4CfgAddrs"&gt;
         *                                         &lt;complexType&gt;
         *                                           &lt;complexContent&gt;
         *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                               &lt;sequence&gt;
         *                                                 &lt;element name="am4CfgAddr"&gt;
         *                                                   &lt;complexType&gt;
         *                                                     &lt;complexContent&gt;
         *                                                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                                                         &lt;sequence&gt;
         *                                                           &lt;element name="subnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                                           &lt;element name="addrType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                                           &lt;element name="ifIpAddr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                                                         &lt;/sequence&gt;
         *                                                       &lt;/restriction&gt;
         *                                                     &lt;/complexContent&gt;
         *                                                   &lt;/complexType&gt;
         *                                                 &lt;/element&gt;
         *                                               &lt;/sequence&gt;
         *                                             &lt;/restriction&gt;
         *                                           &lt;/complexContent&gt;
         *                                         &lt;/complexType&gt;
         *                                       &lt;/element&gt;
         *                                     &lt;/sequence&gt;
         *                                   &lt;/restriction&gt;
         *                                 &lt;/complexContent&gt;
         *                               &lt;/complexType&gt;
         *                             &lt;/element&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *       &lt;/sequence&gt;
         *       &lt;attribute name="xmlns1" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
         *       &lt;attribute name="content-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *       &lt;attribute name="format-version" type="{http://www.w3.org/2001/XMLSchema}int" /&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "interfaces"
        })
        public static class Ifm {

            @XmlElement(required = true)
            protected RpcReply.Data.Ifm.Interfaces interfaces;
            @XmlAttribute(name = "xmlns1")
            protected String xmlns1;
            @XmlAttribute(name = "content-version")
            protected Integer contentVersion;
            @XmlAttribute(name = "format-version")
            protected Integer formatVersion;

            /**
             * Gets the value of the interfaces property.
             * 
             * @return
             *     possible object is
             *     {@link RpcReply.Data.Ifm.Interfaces }
             *     
             */
            public RpcReply.Data.Ifm.Interfaces getInterfaces() {
                return interfaces;
            }

            /**
             * Sets the value of the interfaces property.
             * 
             * @param value
             *     allowed object is
             *     {@link RpcReply.Data.Ifm.Interfaces }
             *     
             */
            public void setInterfaces(RpcReply.Data.Ifm.Interfaces value) {
                this.interfaces = value;
            }

            /**
             * Gets the value of the xmlns1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getXmlns1() {
                return xmlns1;
            }

            /**
             * Sets the value of the xmlns1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setXmlns1(String value) {
                this.xmlns1 = value;
            }

            /**
             * Gets the value of the contentVersion property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getContentVersion() {
                return contentVersion;
            }

            /**
             * Sets the value of the contentVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setContentVersion(Integer value) {
                this.contentVersion = value;
            }

            /**
             * Gets the value of the formatVersion property.
             * 
             * @return
             *     possible object is
             *     {@link Integer }
             *     
             */
            public Integer getFormatVersion() {
                return formatVersion;
            }

            /**
             * Sets the value of the formatVersion property.
             * 
             * @param value
             *     allowed object is
             *     {@link Integer }
             *     
             */
            public void setFormatVersion(Integer value) {
                this.formatVersion = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="interface"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="ifName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="ifmAm4"&gt;
             *                     &lt;complexType&gt;
             *                       &lt;complexContent&gt;
             *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                           &lt;sequence&gt;
             *                             &lt;element name="am4CfgAddrs"&gt;
             *                               &lt;complexType&gt;
             *                                 &lt;complexContent&gt;
             *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                                     &lt;sequence&gt;
             *                                       &lt;element name="am4CfgAddr"&gt;
             *                                         &lt;complexType&gt;
             *                                           &lt;complexContent&gt;
             *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                                               &lt;sequence&gt;
             *                                                 &lt;element name="subnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                                                 &lt;element name="addrType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                                                 &lt;element name="ifIpAddr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                                               &lt;/sequence&gt;
             *                                             &lt;/restriction&gt;
             *                                           &lt;/complexContent&gt;
             *                                         &lt;/complexType&gt;
             *                                       &lt;/element&gt;
             *                                     &lt;/sequence&gt;
             *                                   &lt;/restriction&gt;
             *                                 &lt;/complexContent&gt;
             *                               &lt;/complexType&gt;
             *                             &lt;/element&gt;
             *                           &lt;/sequence&gt;
             *                         &lt;/restriction&gt;
             *                       &lt;/complexContent&gt;
             *                     &lt;/complexType&gt;
             *                   &lt;/element&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "_interface"
            })
            public static class Interfaces {

                @XmlElement(name = "interface", required = true)
                protected RpcReply.Data.Ifm.Interfaces.Interface _interface;

                /**
                 * Gets the value of the interface property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link RpcReply.Data.Ifm.Interfaces.Interface }
                 *     
                 */
                public RpcReply.Data.Ifm.Interfaces.Interface getInterface() {
                    return _interface;
                }

                /**
                 * Sets the value of the interface property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link RpcReply.Data.Ifm.Interfaces.Interface }
                 *     
                 */
                public void setInterface(RpcReply.Data.Ifm.Interfaces.Interface value) {
                    this._interface = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="ifName" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="ifmAm4"&gt;
                 *           &lt;complexType&gt;
                 *             &lt;complexContent&gt;
                 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                 &lt;sequence&gt;
                 *                   &lt;element name="am4CfgAddrs"&gt;
                 *                     &lt;complexType&gt;
                 *                       &lt;complexContent&gt;
                 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                           &lt;sequence&gt;
                 *                             &lt;element name="am4CfgAddr"&gt;
                 *                               &lt;complexType&gt;
                 *                                 &lt;complexContent&gt;
                 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *                                     &lt;sequence&gt;
                 *                                       &lt;element name="subnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                                       &lt;element name="addrType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                                       &lt;element name="ifIpAddr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *                                     &lt;/sequence&gt;
                 *                                   &lt;/restriction&gt;
                 *                                 &lt;/complexContent&gt;
                 *                               &lt;/complexType&gt;
                 *                             &lt;/element&gt;
                 *                           &lt;/sequence&gt;
                 *                         &lt;/restriction&gt;
                 *                       &lt;/complexContent&gt;
                 *                     &lt;/complexType&gt;
                 *                   &lt;/element&gt;
                 *                 &lt;/sequence&gt;
                 *               &lt;/restriction&gt;
                 *             &lt;/complexContent&gt;
                 *           &lt;/complexType&gt;
                 *         &lt;/element&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "ifName",
                    "ifmAm4"
                })
                public static class Interface {

                    @XmlElement(required = true)
                    protected String ifName;
                    @XmlElement(required = true)
                    protected RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 ifmAm4;

                    /**
                     * Gets the value of the ifName property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getIfName() {
                        return ifName;
                    }

                    /**
                     * Sets the value of the ifName property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setIfName(String value) {
                        this.ifName = value;
                    }

                    /**
                     * Gets the value of the ifmAm4 property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 }
                     *     
                     */
                    public RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 getIfmAm4() {
                        return ifmAm4;
                    }

                    /**
                     * Sets the value of the ifmAm4 property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 }
                     *     
                     */
                    public void setIfmAm4(RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 value) {
                        this.ifmAm4 = value;
                    }


                    /**
                     * <p>Java class for anonymous complex type.
                     * 
                     * <p>The following schema fragment specifies the expected content contained within this class.
                     * 
                     * <pre>
                     * &lt;complexType&gt;
                     *   &lt;complexContent&gt;
                     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *       &lt;sequence&gt;
                     *         &lt;element name="am4CfgAddrs"&gt;
                     *           &lt;complexType&gt;
                     *             &lt;complexContent&gt;
                     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *                 &lt;sequence&gt;
                     *                   &lt;element name="am4CfgAddr"&gt;
                     *                     &lt;complexType&gt;
                     *                       &lt;complexContent&gt;
                     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                     *                           &lt;sequence&gt;
                     *                             &lt;element name="subnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *                             &lt;element name="addrType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *                             &lt;element name="ifIpAddr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                     *                           &lt;/sequence&gt;
                     *                         &lt;/restriction&gt;
                     *                       &lt;/complexContent&gt;
                     *                     &lt;/complexType&gt;
                     *                   &lt;/element&gt;
                     *                 &lt;/sequence&gt;
                     *               &lt;/restriction&gt;
                     *             &lt;/complexContent&gt;
                     *           &lt;/complexType&gt;
                     *         &lt;/element&gt;
                     *       &lt;/sequence&gt;
                     *     &lt;/restriction&gt;
                     *   &lt;/complexContent&gt;
                     * &lt;/complexType&gt;
                     * </pre>
                     * 
                     * 
                     */
                    @XmlAccessorType(XmlAccessType.FIELD)
                    @XmlType(name = "", propOrder = {
                        "am4CfgAddrs"
                    })
                    public static class IfmAm4 {

                        @XmlElement(required = true)
                        protected RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs am4CfgAddrs;

                        /**
                         * Gets the value of the am4CfgAddrs property.
                         * 
                         * @return
                         *     possible object is
                         *     {@link RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs }
                         *     
                         */
                        public RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs getAm4CfgAddrs() {
                            return am4CfgAddrs;
                        }

                        /**
                         * Sets the value of the am4CfgAddrs property.
                         * 
                         * @param value
                         *     allowed object is
                         *     {@link RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs }
                         *     
                         */
                        public void setAm4CfgAddrs(RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs value) {
                            this.am4CfgAddrs = value;
                        }


                        /**
                         * <p>Java class for anonymous complex type.
                         * 
                         * <p>The following schema fragment specifies the expected content contained within this class.
                         * 
                         * <pre>
                         * &lt;complexType&gt;
                         *   &lt;complexContent&gt;
                         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                         *       &lt;sequence&gt;
                         *         &lt;element name="am4CfgAddr"&gt;
                         *           &lt;complexType&gt;
                         *             &lt;complexContent&gt;
                         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                         *                 &lt;sequence&gt;
                         *                   &lt;element name="subnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                         *                   &lt;element name="addrType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                         *                   &lt;element name="ifIpAddr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                         *                 &lt;/sequence&gt;
                         *               &lt;/restriction&gt;
                         *             &lt;/complexContent&gt;
                         *           &lt;/complexType&gt;
                         *         &lt;/element&gt;
                         *       &lt;/sequence&gt;
                         *     &lt;/restriction&gt;
                         *   &lt;/complexContent&gt;
                         * &lt;/complexType&gt;
                         * </pre>
                         * 
                         * 
                         */
                        @XmlAccessorType(XmlAccessType.FIELD)
                        @XmlType(name = "", propOrder = {
                            "am4CfgAddr"
                        })
                        public static class Am4CfgAddrs {

                            @XmlElement(required = true)
                            protected RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs.Am4CfgAddr am4CfgAddr;

                            /**
                             * Gets the value of the am4CfgAddr property.
                             * 
                             * @return
                             *     possible object is
                             *     {@link RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs.Am4CfgAddr }
                             *     
                             */
                            public RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs.Am4CfgAddr getAm4CfgAddr() {
                                return am4CfgAddr;
                            }

                            /**
                             * Sets the value of the am4CfgAddr property.
                             * 
                             * @param value
                             *     allowed object is
                             *     {@link RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs.Am4CfgAddr }
                             *     
                             */
                            public void setAm4CfgAddr(RpcReply.Data.Ifm.Interfaces.Interface.IfmAm4 .Am4CfgAddrs.Am4CfgAddr value) {
                                this.am4CfgAddr = value;
                            }


                            /**
                             * <p>Java class for anonymous complex type.
                             * 
                             * <p>The following schema fragment specifies the expected content contained within this class.
                             * 
                             * <pre>
                             * &lt;complexType&gt;
                             *   &lt;complexContent&gt;
                             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                             *       &lt;sequence&gt;
                             *         &lt;element name="subnetMask" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                             *         &lt;element name="addrType" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                             *         &lt;element name="ifIpAddr" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                             *       &lt;/sequence&gt;
                             *     &lt;/restriction&gt;
                             *   &lt;/complexContent&gt;
                             * &lt;/complexType&gt;
                             * </pre>
                             * 
                             * 
                             */
                            @XmlAccessorType(XmlAccessType.FIELD)
                            @XmlType(name = "", propOrder = {
                                "subnetMask",
                                "addrType",
                                "ifIpAddr"
                            })
                            public static class Am4CfgAddr {

                                @XmlElement(required = true)
                                protected String subnetMask;
                                @XmlElement(required = true)
                                protected String addrType;
                                @XmlElement(required = true)
                                protected String ifIpAddr;

                                /**
                                 * Gets the value of the subnetMask property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getSubnetMask() {
                                    return subnetMask;
                                }

                                /**
                                 * Sets the value of the subnetMask property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setSubnetMask(String value) {
                                    this.subnetMask = value;
                                }

                                /**
                                 * Gets the value of the addrType property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getAddrType() {
                                    return addrType;
                                }

                                /**
                                 * Sets the value of the addrType property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setAddrType(String value) {
                                    this.addrType = value;
                                }

                                /**
                                 * Gets the value of the ifIpAddr property.
                                 * 
                                 * @return
                                 *     possible object is
                                 *     {@link String }
                                 *     
                                 */
                                public String getIfIpAddr() {
                                    return ifIpAddr;
                                }

                                /**
                                 * Sets the value of the ifIpAddr property.
                                 * 
                                 * @param value
                                 *     allowed object is
                                 *     {@link String }
                                 *     
                                 */
                                public void setIfIpAddr(String value) {
                                    this.ifIpAddr = value;
                                }

                            }

                        }

                    }

                }

            }

        }

    }

}
