/*
* Generated file
*
<<<<<<< HEAD
* Generated from: yang module name: fabric-factory yang module local name: fabric-factory
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Oct 21 09:42:55 CST 2015
=======
* Generated from: yang module name: fabric-impl yang module local name: fabric-factory
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Nov 04 19:40:41 CST 2015
>>>>>>> 788d9c8... implement fabric api.
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.fabric.impl;
public class FabricFactoryModuleFactory extends org.opendaylight.controller.config.yang.config.fabric.impl.AbstractFabricFactoryModuleFactory {

    @Override
    public org.opendaylight.controller.config.spi.Module createModule(String instanceName, org.opendaylight.controller.config.api.DependencyResolver dependencyResolver, org.osgi.framework.BundleContext bundleContext) {

        return super.createModule(instanceName, dependencyResolver, bundleContext);
    }
}
