/*
* Generated file
*
* Generated from: yang module name: fabric-factory yang module local name: fabric-factory
* Generated by: org.opendaylight.controller.config.yangjmxgenerator.plugin.JMXGenerator
* Generated at: Wed Oct 21 09:42:55 CST 2015
*
* Do not modify this file unless it is present under src/main directory
*/
package org.opendaylight.controller.config.yang.config.fabric.impl;
public class FabricFactoryModuleFactory extends org.opendaylight.controller.config.yang.config.fabric.impl.AbstractFabricFactoryModuleFactory {

}
